export default string = {
  appName: "AgrHub Camera",
  welcome: 'Welcome',
  email: 'Email',
  password: 'Password',
  confirmPassword: 'Confirm password',
  forgotPassword: 'Forgot password',
  tandc: "I have read, understand and agree to the Term of Use and Privacy Policy",
  login: "Login",
  signUp: 'Sign up',
  register: "New to",
  camera: "camera",
  cameras: "cameras",
  emailIncorrect: "Your email is not correct",
  passwordIncorrect: "Your password must be bigger 6 charactor",
  loginFail: "Your email or password is not correct, please try again!",
  profileManagerment: "Profile Managerment",
  notificationCenter: "Notification Center",
  feedback: "FAQ & Feedback",
  About: "About",
  Settings: "Settings",
  logout: "Logout",
}